version: 2
updates:
- package-ecosystem: bundler
  directory: "/evaluator_api"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: unicorn
    versions:
    - 5.8.0
