inherit_from:
  - .disabled.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'evaluator_api/bin/**/*'
    - 'evaluator_api/tmp/**/*'
    - 'client/**/*'
    - 'evaluator_api/db/**/*'
    - 'evaluator_api/spec/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30