source 'https://rubygems.org'
#git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
gem 'unicorn'
gem 'pg', '~> 1.1'
gem 'bootsnap', '~> 1.1', require: false

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'


gem 'sidekiq', '~> 5.2'
gem 'pry-rails'
gem 'redis', '~> 4.2'
gem 'hiredis', '~> 0.6'
gem 'rbnacl', '~> 6.0'
gem 'argon2', '~> 2.0'
gem 'jwt', '~> 2.1'
gem 'kaminari', '~> 1.1'
gem 'openssl', '~> 2.1'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'shoulda-matchers', '~> 4.0'
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_bot_rails', '~> 5.0'
  gem 'faker', '~> 1.9'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'email_spec', '~> 2.2'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rubocop'
  gem 'annotate', '~> 2.7'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
