
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 120

development:
  <<: *default
  database: evaluator_development
  username: evaluator
  password: evaluator
  min_messages: warning

test:
  <<: *default
  database: evaluator_testing
  username: evaluator
  password: evaluator
  min_messages: warning

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_DB_POOL', 1) %>